# Generated by Django 4.2.6 on 2024-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff_dist_staff_pin_staff_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
