# Generated by Django 4.2.6 on 2024-02-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_dist_student_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
