# Generated by Django 4.2.6 on 2024-02-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='replay',
            new_name='reply',
        ),
    ]
