# Generated by Django 4.2.6 on 2024-03-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_replay_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
