# Generated by Django 4.2.6 on 2024-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
