# Generated by Django 4.0.1 on 2024-04-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_staff_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='photo',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
