# Generated by Django 4.0.1 on 2024-04-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_photo_attendance_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.CharField(default='09:00', max_length=15),
        ),
    ]
