
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('login/',views.login),
    path('login_post/',views.login_post),
    path('admin_add_authority/',views.admin_add_authority),
    path('admin_add_authority_post/',views.admin_add_authority_post),
    path('admin_Add_course/',views.admin_Add_course),
    path('admin_Add_course_post/',views.admin_Add_course_post),
    path('admin_Add_dept/',views.admin_Add_dept),
    path('admin_Add_dept_post/',views.admin_Add_dept_post),
    path('edit_dept_post/',views.edit_dept_post),
    path('edit_staff_post/',views.edit_staff_post),
    path('edit_student_post/',views.edit_student_post),
    path('edit_authority_post/',views.edit_authority_post),
    path('edit_course_post/',views.edit_course_post),
    path('admin_Add_staff/',views.admin_Add_staff),
    path('admin_Add_staff_post/',views.admin_Add_staff_post),
    path('admin_add_student/',views.admin_add_student),
    path('admin_add_student_post/',views.admin_add_student_post),
    path('admin_view_attendance/',views.admin_view_attendance),
    path('admin_view_attendance_post/',views.admin_view_attendance_post),
    path('admin_view_authority/',views.admin_view_authority),
    path('admin_view_authority_post/',views.admin_view_authority_post),
    path('admin_view_complaint/',views.admin_view_complaint),
    path('admin_view_complaint_post/',views.admin_view_complaint_post),
    path('admin_view_course/',views.admin_view_course),
    path('admin_view_course_post/',views.admin_view_course_post),
    path('admin_view_dept/',views.admin_view_dept),
    path('admin_change_password/',views.admin_change_password),
    path('admin_change_password_post/',views.admin_change_password_post),
    path('authority_change_password/',views.authority_change_password),
    path('authority_change_password_post/',views.authority_change_password_post),
    path('send_reply/<id>',views.send_reply),
    path('send_reply_post/',views.send_reply_post),

    path('admin_view_dept_post/',views.admin_view_dept_post),
    path('admin_view_late_notification/',views.admin_view_late_notification),
    path('admin_view_late_notification_post/',views.admin_view_late_notification_post),
    path('admin_view_staff/',views.admin_view_staff),
    path('admin_view_staff_post/',views.admin_view_staff_post),
    path('admin_view_student/',views.admin_view_student),
    path('admin_view_student_post/',views.admin_view_student_post),
    path('admin_view_violence/',views.admin_view_violence),
    path('admin_home/',views.admin_home),
    path('authority_home/',views.authority_home),
    path('delete_dept/<id>',views.delete_dept),
    path('delete_course/<id>',views.delete_course),
    path('delete_staff/<id>',views.delete_staff),
    path('delete_student/<id>',views.delete_student),
    path('delete_authority/<id>',views.delete_authority),
    path('included_faces/<id>',views.included_faces),
    path('authority_view_attendance/',views.authority_view_attendance),
    path('authority_view_profile/',views.authority_view_profile),
    path('authority_view_student/',views.authority_view_student),
    path('authority_view_student_post/',views.authority_view_student_post),
    path('edit_dept/<id>',views.edit_dept),
    path('edit_course/<id>',views.edit_course),
    path('edit_staff/<id>',views.edit_staff),
    path('edit_student/<id>',views.edit_student),
    path('edit_authority/<id>',views.edit_authority),
    path('authority_view_violence/',views.authority_view_violence),
    path('view_included_faces/<id>',views.view_included_faces),


    path('andLogin/',views.andLogin),
    path('staff_view_profile/',views.staff_view_profile),
    path('student_view_profile/',views.student_view_profile),
    path('parent_view_student/',views.parent_view_student),
    path('parent_view_authority/',views.parent_view_authority),
    path('parent_view_staff/',views.parent_view_staff),
    path('parent_view_violence/',views.parent_view_violence),
    path('parent_view_attendance/',views.parent_view_attendance),
    path('student_view_attendance/',views.student_view_attendance),
    path('student_view_issue_list/',views.student_view_issue_list),
    path('staff_view_attendance/',views.staff_view_attendance),
    path('staff_view_violence/',views.staff_view_violence),
    path('staff_change_password/',views.staff_change_password),
    path('student_change_password/',views.student_change_password),
    path('parent_change_password/',views.parent_change_password),
    path('send_complaint/',views.send_complaint),
    path('view_reply/',views.view_reply),
    path('staff_view_student/',views.staff_view_student),
    path('get_alert/',views.get_alert),
    path('get_alert_staff/',views.get_alert_staff),


    path('viewattendance/',views.viewattendance),
    path('viewattendance_post/',views.viewattendance_post),


    path('chat/<id>',views.chat1),
    path('chat_view/',views.chat_view),
    path('chat_send/<msg>',views.chat_send),
    path('User_sendchat/',views.User_sendchat),
    path('User_viewchat/',views.User_viewchat),

]
